
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Slide` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Slide
 * ///////////////////
 * ///////////////////
 */
export type SlideModel = runtime.Types.Result.DefaultSelection<Prisma.$SlidePayload>

export type AggregateSlide = {
  _count: SlideCountAggregateOutputType | null
  _min: SlideMinAggregateOutputType | null
  _max: SlideMaxAggregateOutputType | null
}

export type SlideMinAggregateOutputType = {
  id: string | null
  badge: string | null
  title: string | null
  description: string | null
  link: string | null
  image: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SlideMaxAggregateOutputType = {
  id: string | null
  badge: string | null
  title: string | null
  description: string | null
  link: string | null
  image: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SlideCountAggregateOutputType = {
  id: number
  badge: number
  title: number
  description: number
  link: number
  image: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SlideMinAggregateInputType = {
  id?: true
  badge?: true
  title?: true
  description?: true
  link?: true
  image?: true
  createdAt?: true
  updatedAt?: true
}

export type SlideMaxAggregateInputType = {
  id?: true
  badge?: true
  title?: true
  description?: true
  link?: true
  image?: true
  createdAt?: true
  updatedAt?: true
}

export type SlideCountAggregateInputType = {
  id?: true
  badge?: true
  title?: true
  description?: true
  link?: true
  image?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SlideAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Slide to aggregate.
   */
  where?: Prisma.SlideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slides to fetch.
   */
  orderBy?: Prisma.SlideOrderByWithRelationInput | Prisma.SlideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SlideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Slides
  **/
  _count?: true | SlideCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SlideMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SlideMaxAggregateInputType
}

export type GetSlideAggregateType<T extends SlideAggregateArgs> = {
      [P in keyof T & keyof AggregateSlide]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSlide[P]>
    : Prisma.GetScalarType<T[P], AggregateSlide[P]>
}




export type SlideGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SlideWhereInput
  orderBy?: Prisma.SlideOrderByWithAggregationInput | Prisma.SlideOrderByWithAggregationInput[]
  by: Prisma.SlideScalarFieldEnum[] | Prisma.SlideScalarFieldEnum
  having?: Prisma.SlideScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SlideCountAggregateInputType | true
  _min?: SlideMinAggregateInputType
  _max?: SlideMaxAggregateInputType
}

export type SlideGroupByOutputType = {
  id: string
  badge: string
  title: string
  description: string
  link: string
  image: string
  createdAt: Date
  updatedAt: Date
  _count: SlideCountAggregateOutputType | null
  _min: SlideMinAggregateOutputType | null
  _max: SlideMaxAggregateOutputType | null
}

type GetSlideGroupByPayload<T extends SlideGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SlideGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SlideGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SlideGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SlideGroupByOutputType[P]>
      }
    >
  >



export type SlideWhereInput = {
  AND?: Prisma.SlideWhereInput | Prisma.SlideWhereInput[]
  OR?: Prisma.SlideWhereInput[]
  NOT?: Prisma.SlideWhereInput | Prisma.SlideWhereInput[]
  id?: Prisma.StringFilter<"Slide"> | string
  badge?: Prisma.StringFilter<"Slide"> | string
  title?: Prisma.StringFilter<"Slide"> | string
  description?: Prisma.StringFilter<"Slide"> | string
  link?: Prisma.StringFilter<"Slide"> | string
  image?: Prisma.StringFilter<"Slide"> | string
  createdAt?: Prisma.DateTimeFilter<"Slide"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Slide"> | Date | string
}

export type SlideOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  badge?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  link?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlideWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SlideWhereInput | Prisma.SlideWhereInput[]
  OR?: Prisma.SlideWhereInput[]
  NOT?: Prisma.SlideWhereInput | Prisma.SlideWhereInput[]
  badge?: Prisma.StringFilter<"Slide"> | string
  title?: Prisma.StringFilter<"Slide"> | string
  description?: Prisma.StringFilter<"Slide"> | string
  link?: Prisma.StringFilter<"Slide"> | string
  image?: Prisma.StringFilter<"Slide"> | string
  createdAt?: Prisma.DateTimeFilter<"Slide"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Slide"> | Date | string
}, "id">

export type SlideOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  badge?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  link?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SlideCountOrderByAggregateInput
  _max?: Prisma.SlideMaxOrderByAggregateInput
  _min?: Prisma.SlideMinOrderByAggregateInput
}

export type SlideScalarWhereWithAggregatesInput = {
  AND?: Prisma.SlideScalarWhereWithAggregatesInput | Prisma.SlideScalarWhereWithAggregatesInput[]
  OR?: Prisma.SlideScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SlideScalarWhereWithAggregatesInput | Prisma.SlideScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  badge?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  title?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  description?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  link?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  image?: Prisma.StringWithAggregatesFilter<"Slide"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Slide"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Slide"> | Date | string
}

export type SlideCreateInput = {
  id?: string
  badge: string
  title: string
  description: string
  link: string
  image: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlideUncheckedCreateInput = {
  id?: string
  badge: string
  title: string
  description: string
  link: string
  image: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlideUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  badge?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlideUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  badge?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlideCreateManyInput = {
  id?: string
  badge: string
  title: string
  description: string
  link: string
  image: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlideUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  badge?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlideUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  badge?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlideCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  badge?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  link?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlideMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  badge?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  link?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlideMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  badge?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  link?: Prisma.SortOrder
  image?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type SlideSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  badge?: boolean
  title?: boolean
  description?: boolean
  link?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["slide"]>

export type SlideSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  badge?: boolean
  title?: boolean
  description?: boolean
  link?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["slide"]>

export type SlideSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  badge?: boolean
  title?: boolean
  description?: boolean
  link?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["slide"]>

export type SlideSelectScalar = {
  id?: boolean
  badge?: boolean
  title?: boolean
  description?: boolean
  link?: boolean
  image?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SlideOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "badge" | "title" | "description" | "link" | "image" | "createdAt" | "updatedAt", ExtArgs["result"]["slide"]>

export type $SlidePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Slide"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    badge: string
    title: string
    description: string
    link: string
    image: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["slide"]>
  composites: {}
}

export type SlideGetPayload<S extends boolean | null | undefined | SlideDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SlidePayload, S>

export type SlideCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SlideFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SlideCountAggregateInputType | true
  }

export interface SlideDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Slide'], meta: { name: 'Slide' } }
  /**
   * Find zero or one Slide that matches the filter.
   * @param {SlideFindUniqueArgs} args - Arguments to find a Slide
   * @example
   * // Get one Slide
   * const slide = await prisma.slide.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SlideFindUniqueArgs>(args: Prisma.SelectSubset<T, SlideFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Slide that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SlideFindUniqueOrThrowArgs} args - Arguments to find a Slide
   * @example
   * // Get one Slide
   * const slide = await prisma.slide.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SlideFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SlideFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slide that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideFindFirstArgs} args - Arguments to find a Slide
   * @example
   * // Get one Slide
   * const slide = await prisma.slide.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SlideFindFirstArgs>(args?: Prisma.SelectSubset<T, SlideFindFirstArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slide that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideFindFirstOrThrowArgs} args - Arguments to find a Slide
   * @example
   * // Get one Slide
   * const slide = await prisma.slide.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SlideFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SlideFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Slides that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Slides
   * const slides = await prisma.slide.findMany()
   * 
   * // Get first 10 Slides
   * const slides = await prisma.slide.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const slideWithIdOnly = await prisma.slide.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SlideFindManyArgs>(args?: Prisma.SelectSubset<T, SlideFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Slide.
   * @param {SlideCreateArgs} args - Arguments to create a Slide.
   * @example
   * // Create one Slide
   * const Slide = await prisma.slide.create({
   *   data: {
   *     // ... data to create a Slide
   *   }
   * })
   * 
   */
  create<T extends SlideCreateArgs>(args: Prisma.SelectSubset<T, SlideCreateArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Slides.
   * @param {SlideCreateManyArgs} args - Arguments to create many Slides.
   * @example
   * // Create many Slides
   * const slide = await prisma.slide.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SlideCreateManyArgs>(args?: Prisma.SelectSubset<T, SlideCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Slides and returns the data saved in the database.
   * @param {SlideCreateManyAndReturnArgs} args - Arguments to create many Slides.
   * @example
   * // Create many Slides
   * const slide = await prisma.slide.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Slides and only return the `id`
   * const slideWithIdOnly = await prisma.slide.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SlideCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SlideCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Slide.
   * @param {SlideDeleteArgs} args - Arguments to delete one Slide.
   * @example
   * // Delete one Slide
   * const Slide = await prisma.slide.delete({
   *   where: {
   *     // ... filter to delete one Slide
   *   }
   * })
   * 
   */
  delete<T extends SlideDeleteArgs>(args: Prisma.SelectSubset<T, SlideDeleteArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Slide.
   * @param {SlideUpdateArgs} args - Arguments to update one Slide.
   * @example
   * // Update one Slide
   * const slide = await prisma.slide.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SlideUpdateArgs>(args: Prisma.SelectSubset<T, SlideUpdateArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Slides.
   * @param {SlideDeleteManyArgs} args - Arguments to filter Slides to delete.
   * @example
   * // Delete a few Slides
   * const { count } = await prisma.slide.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SlideDeleteManyArgs>(args?: Prisma.SelectSubset<T, SlideDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Slides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Slides
   * const slide = await prisma.slide.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SlideUpdateManyArgs>(args: Prisma.SelectSubset<T, SlideUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Slides and returns the data updated in the database.
   * @param {SlideUpdateManyAndReturnArgs} args - Arguments to update many Slides.
   * @example
   * // Update many Slides
   * const slide = await prisma.slide.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Slides and only return the `id`
   * const slideWithIdOnly = await prisma.slide.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SlideUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SlideUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Slide.
   * @param {SlideUpsertArgs} args - Arguments to update or create a Slide.
   * @example
   * // Update or create a Slide
   * const slide = await prisma.slide.upsert({
   *   create: {
   *     // ... data to create a Slide
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Slide we want to update
   *   }
   * })
   */
  upsert<T extends SlideUpsertArgs>(args: Prisma.SelectSubset<T, SlideUpsertArgs<ExtArgs>>): Prisma.Prisma__SlideClient<runtime.Types.Result.GetResult<Prisma.$SlidePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Slides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideCountArgs} args - Arguments to filter Slides to count.
   * @example
   * // Count the number of Slides
   * const count = await prisma.slide.count({
   *   where: {
   *     // ... the filter for the Slides we want to count
   *   }
   * })
  **/
  count<T extends SlideCountArgs>(
    args?: Prisma.Subset<T, SlideCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SlideCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Slide.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SlideAggregateArgs>(args: Prisma.Subset<T, SlideAggregateArgs>): Prisma.PrismaPromise<GetSlideAggregateType<T>>

  /**
   * Group by Slide.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlideGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SlideGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SlideGroupByArgs['orderBy'] }
      : { orderBy?: SlideGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SlideGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSlideGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Slide model
 */
readonly fields: SlideFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Slide.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SlideClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Slide model
 */
export interface SlideFieldRefs {
  readonly id: Prisma.FieldRef<"Slide", 'String'>
  readonly badge: Prisma.FieldRef<"Slide", 'String'>
  readonly title: Prisma.FieldRef<"Slide", 'String'>
  readonly description: Prisma.FieldRef<"Slide", 'String'>
  readonly link: Prisma.FieldRef<"Slide", 'String'>
  readonly image: Prisma.FieldRef<"Slide", 'String'>
  readonly createdAt: Prisma.FieldRef<"Slide", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Slide", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Slide findUnique
 */
export type SlideFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter, which Slide to fetch.
   */
  where: Prisma.SlideWhereUniqueInput
}

/**
 * Slide findUniqueOrThrow
 */
export type SlideFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter, which Slide to fetch.
   */
  where: Prisma.SlideWhereUniqueInput
}

/**
 * Slide findFirst
 */
export type SlideFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter, which Slide to fetch.
   */
  where?: Prisma.SlideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slides to fetch.
   */
  orderBy?: Prisma.SlideOrderByWithRelationInput | Prisma.SlideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Slides.
   */
  cursor?: Prisma.SlideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Slides.
   */
  distinct?: Prisma.SlideScalarFieldEnum | Prisma.SlideScalarFieldEnum[]
}

/**
 * Slide findFirstOrThrow
 */
export type SlideFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter, which Slide to fetch.
   */
  where?: Prisma.SlideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slides to fetch.
   */
  orderBy?: Prisma.SlideOrderByWithRelationInput | Prisma.SlideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Slides.
   */
  cursor?: Prisma.SlideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Slides.
   */
  distinct?: Prisma.SlideScalarFieldEnum | Prisma.SlideScalarFieldEnum[]
}

/**
 * Slide findMany
 */
export type SlideFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter, which Slides to fetch.
   */
  where?: Prisma.SlideWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slides to fetch.
   */
  orderBy?: Prisma.SlideOrderByWithRelationInput | Prisma.SlideOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Slides.
   */
  cursor?: Prisma.SlideWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slides.
   */
  skip?: number
  distinct?: Prisma.SlideScalarFieldEnum | Prisma.SlideScalarFieldEnum[]
}

/**
 * Slide create
 */
export type SlideCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * The data needed to create a Slide.
   */
  data: Prisma.XOR<Prisma.SlideCreateInput, Prisma.SlideUncheckedCreateInput>
}

/**
 * Slide createMany
 */
export type SlideCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Slides.
   */
  data: Prisma.SlideCreateManyInput | Prisma.SlideCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Slide createManyAndReturn
 */
export type SlideCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * The data used to create many Slides.
   */
  data: Prisma.SlideCreateManyInput | Prisma.SlideCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Slide update
 */
export type SlideUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * The data needed to update a Slide.
   */
  data: Prisma.XOR<Prisma.SlideUpdateInput, Prisma.SlideUncheckedUpdateInput>
  /**
   * Choose, which Slide to update.
   */
  where: Prisma.SlideWhereUniqueInput
}

/**
 * Slide updateMany
 */
export type SlideUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Slides.
   */
  data: Prisma.XOR<Prisma.SlideUpdateManyMutationInput, Prisma.SlideUncheckedUpdateManyInput>
  /**
   * Filter which Slides to update
   */
  where?: Prisma.SlideWhereInput
  /**
   * Limit how many Slides to update.
   */
  limit?: number
}

/**
 * Slide updateManyAndReturn
 */
export type SlideUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * The data used to update Slides.
   */
  data: Prisma.XOR<Prisma.SlideUpdateManyMutationInput, Prisma.SlideUncheckedUpdateManyInput>
  /**
   * Filter which Slides to update
   */
  where?: Prisma.SlideWhereInput
  /**
   * Limit how many Slides to update.
   */
  limit?: number
}

/**
 * Slide upsert
 */
export type SlideUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * The filter to search for the Slide to update in case it exists.
   */
  where: Prisma.SlideWhereUniqueInput
  /**
   * In case the Slide found by the `where` argument doesn't exist, create a new Slide with this data.
   */
  create: Prisma.XOR<Prisma.SlideCreateInput, Prisma.SlideUncheckedCreateInput>
  /**
   * In case the Slide was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SlideUpdateInput, Prisma.SlideUncheckedUpdateInput>
}

/**
 * Slide delete
 */
export type SlideDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
  /**
   * Filter which Slide to delete.
   */
  where: Prisma.SlideWhereUniqueInput
}

/**
 * Slide deleteMany
 */
export type SlideDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Slides to delete
   */
  where?: Prisma.SlideWhereInput
  /**
   * Limit how many Slides to delete.
   */
  limit?: number
}

/**
 * Slide without action
 */
export type SlideDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slide
   */
  select?: Prisma.SlideSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slide
   */
  omit?: Prisma.SlideOmit<ExtArgs> | null
}
